apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Release.Name }}-config
  namespace: NAME_SPACE
  labels:
    name: CONFIGMAP_NAME
data:
  config.yaml: |
    # configuration
    "log_level": "{{ .Values.config.logLevel }}"
    "model_type": "{{ .Values.config.modelType }}"
    "job": "{{ .Values.config.job }}"
    "path": "{{ .Values.ingress.hosts.paths.path }}"
    "model":
        # the model on GCS
        "method": "{{ .Values.config.model.method }}"
        "project_name": "{{ .Values.config.model.projectName }}"
        "bucket_name": "{{ .Values.config.model.bucketName }}"
        "blob_dir": "{{ .Values.config.model.blobDir }}"
    "input_size": {{ .Values.config.inputSize }}
    "port": {{ .Values.service.port }}