apiVersion: v1
kind: Service
metadata:
  name: {{ include "CHART_NAME.fullname" . }}-svc
  labels:
    {{- include "CHART_NAME.labels" . | nindent 4 }}
  namespace: NAME_SPACE
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "CHART_NAME.selectorLabels" . | nindent 4 }}
